// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://yaxheyenslhvqdivqewr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlheGhleWVuc2xodnFkaXZxZXdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTczNTUsImV4cCI6MjA2MzgzMzM1NX0.CMn_883KX9-8-szFYtHYGlF4ThCzwKowy5I_af5EU0w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});